#!/bin/bash

# To use dev proxy
sed -i "s,https://geoservices.rijkswaterstaat.nl/apps/pdokkaart/proxy.ashx?,/cgi-bin/proxy?url=,g" *.js

# TO USE LOCAL (DEV) pdokkaart api:
#sed -i "s,https://kaart.pdok.nl,https://zuidt.nl/pdokkaart,g" **/*.html



